HarmonyRemake/config/routes.rb
Rails.application.routes.draw do
  get 'dev/devTools'
  get 'basic_pages/Home'
  namespace :web do
    get 'events/calendar'
    get 'events/show'
  end



  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  resources :sections
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "basic_pages#Home"
end

HarmonyRemake/app/models/album.rb
class Album < ApplicationRecord
    has_many :photos
    validates :title, :description, presence: true
end

HarmonyRemake/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

HarmonyRemake/app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :photo
    validates :title, :eventstart, :eventend, presence: true
    

  

end

HarmonyRemake/app/models/page.rb
class Page < ApplicationRecord
    belongs_to :section
	validates :title, presence: true
	has_one_attached :doc
	scope :ordered, -> { order(id: :desc) }
	after_create_commit -> { broadcast_prepend_later_to "pages" }
	after_update_commit -> { broadcast_replace_later_to "pages" }
	after_destroy_commit -> { broadcast_remove_to "pages" }
end

HarmonyRemake/app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :album
    has_one_attached :image
end

HarmonyRemake/app/models/section.rb
class Section < ApplicationRecord
    has_many :pages
	validates :title, :location, presence: true
end

HarmonyRemake/app/models/sponsor.rb
class Sponsor < ApplicationRecord
    has_one_attached :image
    validates :title, presence: true
end

HarmonyRemake/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    

end

HarmonyRemake/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description)
    end
end

HarmonyRemake/app/controllers/dev_controller.rb
class DevController < ApplicationController
  def devTools
  end
end

HarmonyRemake/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.ordered
    
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
    @sections = Section.all
  end

  # GET /pages/1/edit
  def edit
    @sections = Section.all
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
       # format.json { render :show, status: :created, location: @page }
       format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
     #   format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
      #  format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
       # format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :section_id, :position, :page_type, :destination, :visible, :content)
    end
end

HarmonyRemake/app/helpers/albums_helper.rb
module AlbumsHelper
end

HarmonyRemake/app/helpers/application_helper.rb
module ApplicationHelper
end

HarmonyRemake/app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

HarmonyRemake/app/helpers/dev_helper.rb
module DevHelper
end

HarmonyRemake/app/helpers/events_helper.rb
module EventsHelper
end

HarmonyRemake/app/helpers/pages_helper.rb
module PagesHelper
end

HarmonyRemake/app/helpers/photos_helper.rb
module PhotosHelper
end

HarmonyRemake/app/helpers/sections_helper.rb
module SectionsHelper
end

HarmonyRemake/app/helpers/sponsors_helper.rb
module SponsorsHelper
end

HarmonyRemake/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Harmony Club of Worcester</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('https://harmonyclubofworcester.org/assets/hcwLogo-b78312cdba5ec1b95f3c1ea372c49ae8bbc2f1940f53cfc3acda2312efacbc58.png') %>
  </head>

  <body class = "bg-primary">
   
  <nav class="navbar  bg-danger position-sticky top-0 navbar-dark">
  <div class="container">
   <h1 class = "text-light">Harmony Club of Worcester</h1>
    <button class="navbar-toggler bg-primary text-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    Menu  <span class="navbar-toggler-icon "></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav">
      <li class="nav-item">
          <%= link_to "Home", "/basic_pages/Home", class: "nav-link text-light" %>
        </li>

        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Admin Tools", dev_devTools_path, class: "nav-link text-light" %>
        </li>
        <%end%>
        <li class="nav-item">
          <%= link_to "Sponsors", sponsors_path, class: "nav-link text-light" %>
        </li>
        
         <li class="nav-item">
          <%= link_to "Photos", photos_path, class: "nav-link text-light " %>
        </li>
         <li class="nav-item">
          <%= link_to "Albums", albums_path, class: "nav-link text-light" %>
        </li>
        <li class="nav-item">
          <%= link_to "Calendar", web_events_calendar_path, class: "nav-link text-light" %>
        </li>
        
        <% Section.all.each do |section| %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
         <%= section.title %>
            
          </a>
          
          <ul class="dropdown-menu ">
            <% Page.all.each do |page| %>
            <% if page.section_id == section.id %>
            <li><%= link_to page.title, page,  class: "dropdown-item " %></li>
            <li><hr class="dropdown-divider"></li>
            <%end%>
           <% end%>
          </ul>
        </li>
        <% end %>
        
        <li class="nav-item ">
          <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link text-light" %>
          <%else%>
          <%= link_to "Sign In", new_user_session_path, class: "nav-link text-light" %>
          <%end%>
        </li>
        
      </ul>
    </div>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<!----
<div class= "container-fluid">
<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <embed src= "https://cdn.htmlgames.com/Archer/" class = " d-block w-100" >
    </div>
    <div class="carousel-item">
      <embed src= "https://cdn.htmlgames.com/ColoringMandalas/" class = " d-block w-100" >
    </div>
    <div class="carousel-item">
      <embed src= "https://cdn.htmlgames.com/DunkBalls/" class = " d-block w-100" >
    </div>
    <div class="carousel-item">
      <embed src= "https://cdn.htmlgames.com/AllFivesDomino/" class = " d-block w-100" >
    </div>
    <div class="carousel-item">
    <embed src="https://pg.ignimgs.com/ign/2023/best-buy/qs_2348_1esic_mobile_video.mp4" class = " d-block w-100">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
---->



   <div class = "bg-light container vh-100 ">
    <%= yield %>
 </div>
 <div class= "container-fluid bg-danger text-light p-5 mt-5">
<div class= "row">
    <% if user_signed_in? %>
 <div class = "col-lg-2 text-center">
  <%= link_to "Admin Tools", 'dev/devTools', class: "nav-link" %>
  </div>
  <%end%>
  <div class = "col-lg-2 text-center">
  <%= link_to "Sponsors", sponsors_path, class: "nav-link" %>
  </div>
  <div class = "col-lg-2 text-center">
  <%= link_to "Albums", albums_path, class: "nav-link " %>
  </div>
  <div class = "col-lg-2 text-center">
  <%= link_to "Photos", photos_path, class: "nav-link " %>
  </div>
  <div class = "col-lg-2 text-center">
  <%= link_to "Calendar", web_events_calendar_path, class: "nav-link " %>
  </div>
  <div class= "row">
  <% Section.all.each do |section| %>
        <div class="nav-item dropdown col-lg-1">
          <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
         <%= section.title%>
            
          </a>
          
          <ul class="dropdown-menu ">
            <% Page.all.each do |page| %>
            <% if page.section_id == section.id %>
            <li><%= link_to page.title, page,  class: "dropdown-item " %></li>
            <li><hr class="dropdown-divider"></li>
            <%end%>
           <% end%>
          </ul>
        </div>
        <% end %>
        </div>

</div>
 </div>
  </body>
</html>

HarmonyRemake/app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :section_id, style: "display: block" %>
    <%= collection_select(:page, :section_id, @sections, :id, :title, {:prompt => false}) %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :page_type, style: "display: block" %>
    <%= form.text_field :page_type %>
  </div>

  <div>
    <%= form.label :destination, style: "display: block" %>
    <%= form.text_field :destination %>
  </div>

  <div>
    <%= form.label :visible, style: "display: block" %>
    <%= form.check_box :visible %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>
    <div>
      <%= form.label :doc, style: "display: block" %>
    <%= form.file_field :doc %>
  </div>

  <div>
    <%= link_to "Cancel", pages_path, class: "btn btn--light" %>
    <%= form.submit %>
  </div>
<% end %>

HarmonyRemake/app/views/pages/_page.html.erb
<div class= "container-fixed float-top">

<%= turbo_frame_tag page do %>
<div id="<%= dom_id page %>" class="container bg-light topPadding pb-2">




<header class="masthead bg-light text-center">
  <div class="container d-flex align-items-center flex-column">
    
  	<h1 class="masthead-heading text-uppercase mb-0">
    <%= link_to page.title,
                page_path(page),
                data: { turbo_frame: "_top" } %>
                </h1>
  </div>
  
  <hr>
  <p class="fs-6 fw-bold"><%= page.content %></p>


</header>

  <%= link_to "Edit",
                  edit_page_path(page),
                  class: "btn btn--light" %>
    </div>
    <% end %>
    </div>

HarmonyRemake/app/views/pages/create.turbo_stream.erb
<%# app/views/pages/create.turbo_stream.erb %>

<%= turbo_stream.prepend "pages", @page %>
<%= turbo_stream.update Page.new, "" %>

HarmonyRemake/app/views/pages/destroy.turbo_stream.erb
<%# app/views/page/destroy.turbo_stream.erb %>

<%= turbo_stream.remove @page %>

HarmonyRemake/app/views/pages/edit.html.erb
<h1>Editing page</h1>
 <%= turbo_frame_tag @page do %>
<%= render "form", page: @page %>
<% end %>
<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

HarmonyRemake/app/views/pages/index.html.erb
<main class="container">
<%= turbo_stream_from "quotes" %>


<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">

  <% @pages.each do |page| %>
    <%= turbo_frame_tag "second_frame" do %>
    <%= render page %>
    <% end %>

  <% end %>
</div>
<div class= "container">
 <%= turbo_frame_tag "first_turbo_frame" do %>
<% if user_signed_in? %>
<%= link_to "New page",
                new_page_path,
                class: "btn btn--primary",
                data: { turbo_frame: dom_id(Page.new) } %>
<%end%>
</div>
<%end%>

</main>

HarmonyRemake/app/views/pages/new.html.erb
<div class = "container">
<h1>New page</h1>
  <%= turbo_frame_tag "first_turbo_frame" do %>
<%= render "form", page: @page %>
  <% end %>
<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

</div>

HarmonyRemake/app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>
<% if user_signed_in? %>
<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>
<%end%>